import CustomError from "@utils/CustomError.class";
import catchError from "@utils/catchError";

import managerService from "./manager.service";

const getManagers = catchError(async (req, res) => {});

export { getManagers };
